WITH CART as (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk', 'Yogurt')
)

SELECT CART_ID
FROM CART_PRODUCTS t2
WHERE CART_ID in (SELECT t1.CART_ID
FROM CART t1
WHERE NAME = 'MIlk') and  t2.NAME = 'Yogurt';