WITH CNT AS (
    SELECT PARENT_ID, COUNT(ID) AS idc
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT e.ID,
       CASE 
           WHEN c.idc IS NULL THEN 0
           ELSE c.idc
       END AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT JOIN CNT c ON e.ID = c.PARENT_ID
ORDER BY e.ID;