WITH T1 as (
    SELECT COUNT(USER_ID) as ac
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT 
YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) as MONTH,
COUNT(DISTINCT o.USER_ID) as PUCHASED_USERS,
ROUND(COUNT(DISTINCT i.USER_ID) / T1.ac , 1) as PUCHASED_RATIO
FROM T1,
    USER_INFO i
    JOIN ONLINE_SALE  o
    ON i.USER_ID = o.USER_ID
WHERE YEAR(i.JOINED) = 2021
GROUP BY YEAR, MONTH
order by YEAR, MONTH;


# SELECT COUNT(USER_ID) as ac
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021;