-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD 
FROM PATIENT p, DOCTOR d, APPOINTMENT a
WHERE p.PT_NO = a.PT_NO and a.MDDR_ID = d.DR_ID and a.MCDP_CD = 'cs' and
a.APNT_CNCL_YN = 'N' and MONTH(APNT_YMD)= 04 and YEAR(APNT_YMD)=2022 and DAY(APNT_YMD) = 13
ORDER BY APNT_YMD;