SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD 
FROM PATIENT p
JOIN APPOINTMENT a on p.PT_NO = a.PT_NO
JOIN DOCTOR d on d.DR_ID = a.MDDR_ID
WHERE
a.APNT_CNCL_YN = 'N' 
and TO_CHAR(a.APNT_YMD,'yyyy-MM-dd') = '2022-04-13'
ORDER BY APNT_YMD;