WITH hours AS (
    SELECT LEVEL-1 AS HOUR
    FROM dual
    CONNECT BY LEVEL <= 24
),
animal_hours AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
)
SELECT h.HOUR, COALESCE(ah.COUNT, 0) AS COUNT
FROM hours h
LEFT JOIN animal_hours ah ON h.HOUR = ah.HOUR
ORDER BY h.HOUR;