WITH RECURSIVE TIME_CTE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME_CTE
    WHERE HOUR<23
)

SELECT T.HOUR HOUR, COUNT(O.DATETIME) AS COUNT
FROM ANIMAL_OUTS O RIGHT JOIN TIME_CTE T ON T.HOUR = HOUR(O.DATETIME) 
GROUP BY 1
ORDER BY 1;