-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME,GENDER,TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-dd') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' and TLNO is not null and TO_CHAR(DATE_OF_BIRTH,'MM') = '03'
order by MEMBER_ID;