-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) as "HOUR", COUNT(ANIMAL_ID) as "COUNT"
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(DATETIME,'HH24')) between 9 and 19
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY TO_CHAR(DATETIME,'HH24')