SELECT MEMBER_NAME,REVIEW_TEXT,TO_CHAR(REVIEW_DATE,'yyyy-MM-dd') as REVIEW_DATE
FROM MEMBER_PROFILE p, REST_REVIEW r
WHERE
p.MEMBER_ID = r.MEMBER_ID and
p.MEMBER_ID in
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) in (SELECT MAX(COUNT(MEMBER_ID))
        FROM REST_REVIEW
        GROUP BY MEMBER_ID))
ORDER BY REVIEW_DATE, REVIEW_TEXT;