-- 코드를 입력하세요
SELECT DISTINCT r.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR r
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
on r.CAR_ID = h.CAR_ID
WHERE r.CAR_TYPE='세단' and MONTH(h.START_DATE) = 10
ORDER BY r.CAR_ID desc;
