WITH GROUP_DEVELOPERS AS (
    SELECT 
        ID, 
        EMAIL, 
        GROUP_CONCAT(DISTINCT NAME, CATEGORY) AS GROUPED
    FROM 
        SKILLCODES
    JOIN 
        DEVELOPERS
        ON DEVELOPERS.SKILL_CODE & SKILLCODES.CODE
    GROUP BY 1,2
)
SELECT 
CASE 
WHEN GROUPED like('%Front%') and GROUPED like('%Python%') THEN 'A'
WHEN GROUPED like('%C#%') THEN 'B'
WHEN GROUPED like('%Front%') and GROUPED not like('%Python%') THEN 'C'
END as GRADE,
ID,
EMAIL
FROM GROUP_DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE,ID